FROM nginx:alpine
COPY random-angpau/ /usr/share/nginx/html/
COPY admin-panel/ /usr/share/nginx/html/admin/
COPY images/ /usr/share/nginx/html/images/
COPY favicon/ /usr/share/nginx/html/favicon/
COPY nginx.conf /etc/nginx/conf.d/default.conf